# -*- coding: utf-8 -*-

#############################
import sys
sys.path.append("..")
import os
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWebEngineWidgets import QWebEngineView
from graficas.htmltest import html_Web
from ajustes import mg


class Sinergia(QMainWindow):
	def __init__(self, parent=None):
		super(Sinergia, self).__init__(parent=parent)

		self.setWindowState(Qt.WindowMaximized)
		self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowSystemMenuHint)

		font = QFont()
		font.setFamily("Raleway Thin")
		font.setPointSize(18)
		font.setItalic(True)
		self.setFont(font)

		self.grilla = QWidget()
		self.grilla.setObjectName("grilla")
		self.grid = QGridLayout(self.grilla)
		self.grid.setObjectName("grid")

		self.mr2 = QFrame(self.grilla)
		self.mr2.setMaximumSize(QSize(16777215, 195))
		self.mr2.setFrameShape(QFrame.Box)
		self.mr2.setFrameShadow(QFrame.Plain)
		self.mr2.setObjectName("mr2")

		self.grid2 = QGridLayout(self.mr2)
		self.grid2.setObjectName("grid2")
		self.infbox = QGroupBox(self.mr2)
		self.infbox.setObjectName("infbox")
		self.reticula3 = QGridLayout(self.infbox)
		self.reticula3.setObjectName("reticula3")

		self.foto = QLabel(self.infbox)
		self.foto.setMaximumSize(QSize(150, 16777215))
		self.foto.setFrameShape(QFrame.Panel)
		self.foto.setFrameShadow(QFrame.Plain)
		self.foto.setText("")
		self.foto.setPixmap(QPixmap('{}/img/logo2.jpg'.format(os.getcwd())))
		self.foto.setScaledContents(True)
		self.foto.setObjectName("foto")
		self.reticula3.addWidget(self.foto, 0, 0, 3, 1)

		self.nom = QLabel(self.infbox)
		self.nom.setFrameShape(QFrame.Panel)
		self.nom.setFrameShadow(QFrame.Sunken)
		self.nom.setObjectName("nom")
		self.reticula3.addWidget(self.nom, 0, 1, 1, 1)

		self.corr = QLabel(self.infbox)
		self.corr.setFrameShape(QFrame.Panel)
		self.corr.setFrameShadow(QFrame.Sunken)
		self.corr.setObjectName("corr")
		self.reticula3.addWidget(self.corr, 1, 1, 1, 1)

		self.niv = QLabel(self.infbox)
		self.niv.setFrameShape(QFrame.Panel)
		self.niv.setFrameShadow(QFrame.Sunken)
		self.niv.setObjectName("niv")
		self.reticula3.addWidget(self.niv, 2, 1, 1, 1)
		self.grid2.addWidget(self.infbox, 0, 0, 1, 1)
		self.grid.addWidget(self.mr2, 0, 2, 1, 2)

		self.mr1 = QFrame(self.grilla)
		self.mr1.setMaximumSize(QSize(16777215, 195))
		self.mr1.setFrameShape(QFrame.Box)
		self.mr1.setFrameShadow(QFrame.Plain)
		self.mr1.setObjectName("mr1")
		self.grid1 = QGridLayout(self.mr1)
		self.grid1.setObjectName("grid1")

		self.sigbox = QGroupBox(self.mr1)
		self.sigbox.setObjectName("sigbox")
		self.reticula1 = QGridLayout(self.sigbox)
		self.reticula1.setObjectName("reticula1")

		self.mr6 = QFrame(self.sigbox)
		self.mr6.setMaximumSize(QSize(157, 139))
		self.mr6.setFrameShape(QFrame.Box)
		self.mr6.setFrameShadow(QFrame.Plain)
		self.mr6.setObjectName("mr6")

		self.reticula2 = QGridLayout(self.mr6)
		self.reticula2.setObjectName("reticula2")

		self.acerca = QLabel(self.mr6)
		self.acerca.setMaximumSize(QSize(148, 16777215))
		self.acerca.setCursor(QCursor(Qt.PointingHandCursor))
		self.acerca.setFrameShape(QFrame.Panel)
		self.acerca.setFrameShadow(QFrame.Plain)
		self.acerca.setText("")
		self.acerca.setPixmap(QPixmap(mg('{}/img/acerca.jpg'.format(os.getcwd()))))
		self.acerca.setScaledContents(True)
		self.acerca.setObjectName("acerca")
		self.reticula2.addWidget(self.acerca, 0, 0, 2, 1)

		self.minx = QLabel(self.mr6)
		self.minx.setMaximumSize(QSize(31, 31))
		self.minx.setCursor(QCursor(Qt.PointingHandCursor))
		self.minx.setFrameShape(QFrame.Box)
		self.minx.setText("")
		self.minx.setPixmap(QPixmap(mg('{}/img/min.ico'.format(os.getcwd()))))
		self.minx.setScaledContents(True)
		self.minx.setObjectName("minx")
		self.reticula2.addWidget(self.minx, 0, 1, 1, 1)

		self.sal = QLabel(self.mr6)
		self.sal.setMaximumSize(QSize(31, 31))
		self.sal.setCursor(QCursor(Qt.PointingHandCursor))
		self.sal.setFrameShape(QFrame.Box)
		self.sal.setText("")
		self.sal.setPixmap(QPixmap(mg('{}/img/cierre.ico'.format(os.getcwd()))))
		self.sal.setScaledContents(True)
		self.sal.setObjectName("sal")
		self.reticula2.addWidget(self.sal, 1, 1, 1, 1)
		self.reticula1.addWidget(self.mr6, 0, 1, 1, 1)

		self.logo = QLabel(self.sigbox)
		self.logo.setMaximumSize(QSize(550, 16777215))
		self.logo.setFrameShape(QFrame.Panel)
		self.logo.setFrameShadow(QFrame.Plain)
		self.logo.setText("")
		self.logo.setPixmap(QPixmap('{}/img/logo2.jpg'.format(os.getcwd())))
		self.logo.setScaledContents(True)
		self.logo.setObjectName("logo")
		self.reticula1.addWidget(self.logo, 0, 0, 1, 1)
		self.grid1.addWidget(self.sigbox, 0, 0, 1, 1)
		self.grid.addWidget(self.mr1, 0, 0, 1, 2)

		self.mr4 = QFrame(self.grilla)
		self.mr4.setFrameShape(QFrame.Box)
		self.mr4.setFrameShadow(QFrame.Plain)
		self.mr4.setObjectName("mr4")
		self.grid4 = QGridLayout(self.mr4)
		self.grid4.setObjectName("grid4")

		self.tabla = QTabWidget(self.mr4)
		self.tabla.setObjectName("tabla")
		self.ceja = QWidget()
		self.ceja.setObjectName("ceja")

		self.reticula5 = QGridLayout(self.ceja)
		self.reticula5.setObjectName("reticula5")

		# self.lista = QTableWidget(self.ceja)
		# self.lista.setObjectName("lista")
		# self.lista.setColumnCount(1)
		# self.lista.setRowCount(0)
		# item = QTableWidgetItem()
		# font = QFont()
		# font.setFamily("Raleway Thin")
		# font.setPointSize(14)
		# item.setFont(font)
		# self.lista.setHorizontalHeaderItem(0, item)
		# self.reticula5.addWidget(self.lista, 0, 0, 1, 1)

		# self.htmlw = html_Web()
		# self.htmlw.armar_Html()
		self.web_view = QWebEngineView()
		self.web_view.load(QUrl().fromLocalFile(os.path.split(os.path.abspath(__file__))[0]+r'/test.html'))

		self.reticula5.addWidget(self.web_view, 0, 0, 1, 1)
		self.tabla.addTab(self.ceja, "")
		self.grid4.addWidget(self.tabla, 0, 0, 1, 1)
		self.grid.addWidget(self.mr4, 1, 1, 1, 2)

		self.mr3 = QFrame(self.grilla)
		self.mr3.setMaximumSize(QSize(170, 16777215))
		self.mr3.setFrameShape(QFrame.Box)
		self.mr3.setFrameShadow(QFrame.Plain)
		self.mr3.setObjectName("mr3")

		self.grid3 = QGridLayout(self.mr3)
		self.grid3.setObjectName("grid3")
		self.verbox = QGroupBox(self.mr3)
		self.verbox.setObjectName("verbox")

		self.reticula4 = QGridLayout(self.verbox)
		self.reticula4.setObjectName("reticula4")
		self.j = QLabel(self.verbox)
		self.j.setMaximumSize(QSize(110, 65))
		self.j.setCursor(QCursor(Qt.PointingHandCursor))
		self.j.setFrameShape(QFrame.Box)
		self.j.setText("")
		self.j.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.j.setScaledContents(True)
		self.j.setObjectName("j")
		self.reticula4.addWidget(self.j, 0, 0, 1, 1)

		self.k = QLabel(self.verbox)
		self.k.setMaximumSize(QSize(110, 65))
		self.k.setCursor(QCursor(Qt.PointingHandCursor))
		self.k.setFrameShape(QFrame.Box)
		self.k.setText("")
		self.k.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.k.setScaledContents(True)
		self.k.setObjectName("k")
		self.reticula4.addWidget(self.k, 1, 0, 1, 1)

		self.l = QLabel(self.verbox)
		self.l.setMaximumSize(QSize(110, 65))
		self.l.setCursor(QCursor(Qt.PointingHandCursor))
		self.l.setFrameShape(QFrame.Box)
		self.l.setText("")
		self.l.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.l.setScaledContents(True)
		self.l.setObjectName("l")
		self.reticula4.addWidget(self.l, 2, 0, 1, 1)

		self.m = QLabel(self.verbox)
		self.m.setMaximumSize(QSize(110, 65))
		self.m.setCursor(QCursor(Qt.PointingHandCursor))
		self.m.setFrameShape(QFrame.Box)
		self.m.setText("")
		self.m.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.m.setScaledContents(True)
		self.m.setObjectName("m")
		self.reticula4.addWidget(self.m, 3, 0, 1, 1)

		self.n = QLabel(self.verbox)
		self.n.setMaximumSize(QSize(110, 65))
		self.n.setCursor(QCursor(Qt.PointingHandCursor))
		self.n.setFrameShape(QFrame.Box)
		self.n.setText("")
		self.n.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.n.setScaledContents(True)
		self.n.setObjectName("n")
		self.reticula4.addWidget(self.n, 4, 0, 1, 1)

		self.o = QLabel(self.verbox)
		self.o.setMaximumSize(QSize(110, 65))
		self.o.setCursor(QCursor(Qt.PointingHandCursor))
		self.o.setFrameShape(QFrame.Box)
		self.o.setText("")
		self.o.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.o.setScaledContents(True)
		self.o.setObjectName("o")
		self.reticula4.addWidget(self.o, 5, 0, 1, 1)

		self.p = QLabel(self.verbox)
		self.p.setMaximumSize(QSize(110, 65))
		self.p.setCursor(QCursor(Qt.PointingHandCursor))
		self.p.setFrameShape(QFrame.Box)
		self.p.setText("")
		self.p.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.p.setScaledContents(True)
		self.p.setObjectName("p")
		self.reticula4.addWidget(self.p, 6, 0, 1, 1)

		self.q = QLabel(self.verbox)
		self.q.setMaximumSize(QSize(110, 65))
		self.q.setCursor(QCursor(Qt.PointingHandCursor))
		self.q.setFrameShape(QFrame.Box)
		self.q.setText("")
		self.q.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.q.setScaledContents(True)
		self.q.setObjectName("q")
		self.reticula4.addWidget(self.q, 7, 0, 1, 1)
		self.grid3.addWidget(self.verbox, 0, 0, 1, 1)
		self.grid.addWidget(self.mr3, 1, 0, 1, 1)

		self.mr5 = QFrame(self.grilla)
		self.mr5.setMaximumSize(QSize(170, 16777215))
		self.mr5.setFrameShape(QFrame.Box)
		self.mr5.setFrameShadow(QFrame.Plain)
		self.mr5.setObjectName("mr5")
		self.grid5 = QGridLayout(self.mr5)
		self.grid5.setObjectName("grid5")

		self.regbox = QGroupBox(self.mr5)
		self.regbox.setObjectName("regbox")
		self.reticula6 = QGridLayout(self.regbox)
		self.reticula6.setObjectName("reticula6")

		self.a = QLabel(self.regbox)
		self.a.setMaximumSize(QSize(110, 65))
		self.a.setCursor(QCursor(Qt.PointingHandCursor))
		self.a.setFrameShape(QFrame.Box)
		self.a.setText("")
		self.a.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.a.setScaledContents(True)
		self.a.setObjectName("a")
		self.reticula6.addWidget(self.a, 0, 0, 1, 1)

		self.b = QLabel(self.regbox)
		self.b.setMaximumSize(QSize(110, 65))
		self.b.setCursor(QCursor(Qt.PointingHandCursor))
		self.b.setFrameShape(QFrame.Box)
		self.b.setText("")
		self.b.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.b.setScaledContents(True)
		self.b.setObjectName("b")
		self.reticula6.addWidget(self.b, 1, 0, 1, 1)

		self.c = QLabel(self.regbox)
		self.c.setMaximumSize(QSize(110, 65))
		self.c.setCursor(QCursor(Qt.PointingHandCursor))
		self.c.setFrameShape(QFrame.Box)
		self.c.setText("")
		self.c.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.c.setScaledContents(True)
		self.c.setObjectName("c")
		self.reticula6.addWidget(self.c, 2, 0, 1, 1)

		self.d = QLabel(self.regbox)
		self.d.setMaximumSize(QSize(110, 65))
		self.d.setCursor(QCursor(Qt.PointingHandCursor))
		self.d.setFrameShape(QFrame.Box)
		self.d.setText("")
		self.d.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.d.setScaledContents(True)
		self.d.setObjectName("d")
		self.reticula6.addWidget(self.d, 3, 0, 1, 1)

		self.f = QLabel(self.regbox)
		self.f.setMaximumSize(QSize(110, 65))
		self.f.setCursor(QCursor(Qt.PointingHandCursor))
		self.f.setFrameShape(QFrame.Box)
		self.f.setText("")
		self.f.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.f.setScaledContents(True)
		self.f.setObjectName("f")
		self.reticula6.addWidget(self.f, 4, 0, 1, 1)

		self.g = QLabel(self.regbox)
		self.g.setMaximumSize(QSize(110, 65))
		self.g.setCursor(QCursor(Qt.PointingHandCursor))
		self.g.setFrameShape(QFrame.Box)
		self.g.setText("")
		self.g.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.g.setScaledContents(True)
		self.g.setObjectName("g")
		self.reticula6.addWidget(self.g, 5, 0, 1, 1)

		self.h = QLabel(self.regbox)
		self.h.setMaximumSize(QSize(110, 65))
		self.h.setCursor(QCursor(Qt.PointingHandCursor))
		self.h.setFrameShape(QFrame.Box)
		self.h.setText("")
		self.h.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.h.setScaledContents(True)
		self.h.setObjectName("h")
		self.reticula6.addWidget(self.h, 6, 0, 1, 1)

		self.i = QLabel(self.regbox)
		self.i.setMaximumSize(QSize(110, 65))
		self.i.setCursor(QCursor(Qt.PointingHandCursor))
		self.i.setFrameShape(QFrame.Box)
		self.i.setText("")
		self.i.setPixmap(QPixmap('{}/img/linux.jpg'.format(os.getcwd())))
		self.i.setScaledContents(True)
		self.i.setObjectName("i")
		self.reticula6.addWidget(self.i, 7, 0, 1, 1)
		self.grid5.addWidget(self.regbox, 0, 0, 1, 1)
		self.grid.addWidget(self.mr5, 1, 3, 1, 1)
		self.setCentralWidget(self.grilla)
		# self.actionVer_Almacen = QtWidgets.QAction(principal)
		# self.actionVer_Almacen.setObjectName("actionVer_Almacen")

		self.tabla.setCurrentIndex(0)

		self.infbox.setTitle("Informacion del personal")
		self.nom.setText("Nombre:")
		self.corr.setText("Correo:")
		self.niv.setText("Nivel:")
		self.sigbox.setTitle("Bienvenido a Sinergia !!")
		# item = self.lista.horizontalHeaderItem(0)
		# item.setText("rrrr")


		self.tabla.setTabText(self.tabla.indexOf(self.ceja), ("Pendientes"))
		self.verbox.setTitle("Ver todo")
		self.regbox.setTitle("Registros")


# if __name__ == "__main__":

# 	app = QApplication(sys.argv)
# 	ap = Sinergia()
# 	ap.show()
# 	sys.exit(app.exec_())

